In [4]:
#Q.2) Dataset Name: winequality-red.csv [15]
#Write a program in python to perform following tasks
#a. Rescaling: Normalised the dataset using MinMaxScaler class 
#b. Standardizing Data (transform them into a standard Gaussian distribution with a mean of 0 and 
#a standard deviation of 1)
#c. Normalizing Data ( rescale each observation to a length of 1 (a unit norm). For this, use the Normalizer class.)

import numpy as np
import pandas as pd
from sklearn import preprocessing 
import scipy.stats as s
df=pd.read_csv("E:/winequality-red.csv")

#rescaling data
print("data_scaled into 0 to 1")
data_scaler=preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled=data_scaler.fit_transform(df)
print(data_scaled.round(2))

#standaizing data
x_scaled=preprocessing.scale(df)
x_scaled.mean(axis=0)
x_scaled.std(axis=0)
print("---------------------------------------------------------")
print("\nStanderized data\n",x_scaled.round(2))
print("\nscaled mean\n",s.tmean(x_scaled).round(2))
print("\nscaled standerd deviation\n",round(x_scaled.std(),2))

#normalization data
dn=preprocessing.normalize(df,norm="l1")
print("normalize data")
print(dn.round(2))

data_scaled into 0 to 1
[[0.25 0.4  0.   ... 0.14 0.15 0.4 ]
 [0.28 0.52 0.   ... 0.21 0.22 0.4 ]
 [0.28 0.44 0.04 ... 0.19 0.22 0.4 ]
 ...
 [0.15 0.27 0.13 ... 0.25 0.4  0.6 ]
 [0.12 0.36 0.12 ... 0.23 0.28 0.4 ]
 [0.12 0.13 0.47 ... 0.2  0.4  0.6 ]]
---------------------------------------------------------

Standerized data
 [[-0.53  0.96 -1.39 ... -0.58 -0.96 -0.79]
 [-0.3   1.97 -1.39 ...  0.13 -0.58 -0.79]
 [-0.3   1.3  -1.19 ... -0.05 -0.58 -0.79]
 ...
 [-1.16 -0.1  -0.72 ...  0.54  0.54  0.45]
 [-1.39  0.65 -0.78 ...  0.31 -0.21 -0.79]
 [-1.33 -1.22  1.02 ...  0.01  0.54  0.45]]

scaled mean
 -0.0

scaled standerd deviation
 1.0
normalize data
[[0.1  0.01 0.   ... 0.01 0.13 0.07]
 [0.06 0.01 0.   ... 0.01 0.08 0.04]
 [0.08 0.01 0.   ... 0.01 0.1  0.05]
 ...
 [0.06 0.01 0.   ... 0.01 0.11 0.06]
 [0.06 0.01 0.   ... 0.01 0.1  0.05]
 [0.06 0.   0.01 ... 0.01 0.12 0.06]]


In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing 
import scipy.stats as s
df=pd.read_csv("E:/winequality-red.csv")

#rescaling data
print("data_scaled into 0 to 1")
data_scaler=preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled=data_scaler.fit_transform(df)
print(data_scaled.round(2))

data_scaled into 0 to 1
[[0.25 0.4  0.   ... 0.14 0.15 0.4 ]
 [0.28 0.52 0.   ... 0.21 0.22 0.4 ]
 [0.28 0.44 0.04 ... 0.19 0.22 0.4 ]
 ...
 [0.15 0.27 0.13 ... 0.25 0.4  0.6 ]
 [0.12 0.36 0.12 ... 0.23 0.28 0.4 ]
 [0.12 0.13 0.47 ... 0.2  0.4  0.6 ]]


In [2]:
#standaizing data
x_scaled=preprocessing.scale(df)
x_scaled.mean(axis=0)
x_scaled.std(axis=0)
print("---------------------------------------------------------")
print("\nStanderized data\n",x_scaled.round(2))
print("\nscaled mean\n",s.tmean(x_scaled).round(2))
print("\nscaled standerd deviation\n",round(x_scaled.std(),2))

---------------------------------------------------------

Standerized data
 [[-0.53  0.96 -1.39 ... -0.58 -0.96 -0.79]
 [-0.3   1.97 -1.39 ...  0.13 -0.58 -0.79]
 [-0.3   1.3  -1.19 ... -0.05 -0.58 -0.79]
 ...
 [-1.16 -0.1  -0.72 ...  0.54  0.54  0.45]
 [-1.39  0.65 -0.78 ...  0.31 -0.21 -0.79]
 [-1.33 -1.22  1.02 ...  0.01  0.54  0.45]]

scaled mean
 -0.0

scaled standerd deviation
 1.0
